name: Devlopment Enviroment CD

on:
  workflow_run:
    workflows: ["CI for push"]
    branches: [dev]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: 🔨 Build Project
      run: |
        npm ci
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.ftp_dev_host }}
        username: ${{ secrets.ftp_dev_username }}
        password: ${{ secrets.ftp_dev_password }}
        local-dir: ./dist/site/
        server-dir:  /home/bixos-devsaselus1/
